version: '3'

services:

  mongodb:
    image: mongo:3.4.9
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports: 
      - 27017:27017

  rest-api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8888
        --reload
        --preload
        --access-logfile -
        "memoria.wsgi:app"
    environment:
      - MONGO_HOST=mongodb
      - PYTHONUNBUFFERED='true'

    volumes:
      - '.:/memoria'
    ports:
      - '8888:8888'
    links:
      - mongodb
    depends_on:
      - mongodb
